site_name: CFPA Music Technology Textbook

theme:
  name: material

nav:
  - Home: index.md
  - Composition: composition.md
  - Performance: performance.md
  - Engineering: engineering.md
  - Production: production.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css